name: Build (GNU GCC/C++)

on:
  push:
    branches:
      - 'dev'
  pull_request:
      - 'dev'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        lib: [ ice_cpu ]
        def: [ ICE_CPU_IMPL ]

    steps:
    - uses: actions/checkout@v2
    - name: Check the Branch
      with:
        ref: dev
    - name: Build - Microsoft Windows
      if: matrix.os == 'windows-latest'
      run: |
        if not exist build mkdir build
        copy /y /s rebase/${{ matrix.lib }}.h build/${{ matrix.lib }}.h
        echo '#define ${{ matrix.def }}\n#include "${{ matrix.lib }}.h"\n' > build/${{ matrix.lib }}.c
        gcc -shared build/${{ matrix.lib }}.c -o build/${{ matrix.lib }}.dll
        del build/*.c build/*.h
      
    - name: Build - Linux (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir -p build
        yes | cp -r rebase/${{ matrix.lib }}.h build/${{ matrix.lib }}.h
        echo '#define ${{ matrix.def }}\n#include "${{ matrix.lib }}.h"\n' > build/${{ matrix.lib }}.c
        gcc -shared build/${{ matrix.lib }}.c -o build/${{ matrix.lib }}.so
        rm -f build/*.c build/*.h
      
    - name: Build - macOS/OSX
      if: matrix.os == 'macOS-latest'
      run: |
        mkdir -p build
        yes | cp -r rebase/${{ matrix.lib }}.h build/${{ matrix.lib }}.h
        echo '#define ${{ matrix.def }}\n#include "${{ matrix.lib }}.h"\n' > build/${{ matrix.lib }}.c
        gcc -dynamiclib build/${{ matrix.lib }}.c -o build/${{ matrix.lib }}.dylib
        rm -f build/*.c build/*.h
  
  archive-build-artifacts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        lib: [ ice_cpu ]
        def: [ ICE_CPU_IMPL ]
    
    steps:
    - name: Artifacts Setup & Update - Microsoft Windows
      if: matrix.os == 'windows-latest'
      run: |
        if not exist downloads mkdir downloads
        copy /y /s build/${{ matrix.lib }}.dll downloads/${{ matrix.lib }}.dll
    
    - name: Artifacts Setup & Update - Linux (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir -p downloads
        yes | cp -r build/${{ matrix.lib }}.so downloads/${{ matrix.lib }}.so
    
    - name: Artifacts Setup & Update - macOS/OSX
      if: matrix.os == 'macOS-latest'
      run: |
        mkdir -p downloads
        yes | cp -r build/${{ matrix.lib }}.dylib downloads/${{ matrix.lib }}.dylib
  
    - name: Artifacts - ${{ matrix.os }}
      uses: actions/upload-artifact@v2
      with: 
          name: assets-for-download
          path: downloads
