name: Build (GNU GCC/C++)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        ext: [ .so, .dll, .dylib ]
        lib: [ ice_cpu ]
        def: [ ICE_CPU_IMPL ]
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: Build - ${{ matrix.os }}

      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          if not exist build mkdir build
          copy /y /s rebase/${{ matrix.lib }}.h build/${{ matrix.lib }}.h
          echo '#define ${{ matrix.def }}\n#include ${{ matrix.lib }}\n' > build/${{ matrix.lib }}.c
          gcc build/${{ matrix.lib }}.c -o build/${{ matrix.lib }}${{ matrix.ext }}
          del build/*.c build/*.h
        else
          mkdir -p build
          yes | cp -r rebase/${{ matrix.lib }}.h build/${{ matrix.lib }}.h
          echo '#define ${{ matrix.def }}\n#include ${{ matrix.lib }}\n' > build/${{ matrix.lib }}.c
          gcc build/${{ matrix.lib }}.c -o build/${{ matrix.lib }}${{ matrix.ext }}
          rm -f build/*.c build/*.h
        fi
  
  archive-build-artifacts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        ext: [ .so, .dll, .dylib ]
        lib: [ ice_cpu ]
        def: [ ICE_CPU_IMPL ]
    
    steps:
    - name: Artifacts Setup & Update - ${{ matrix.os }}
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          if not exist downloads mkdir downloads
          copy /y /s build/${{ matrix.lib }}${{ matrix.ext }} downloads/${{ matrix.lib }}${{ matrix.ext }}
        else
          mkdir -p downloads
          yes | cp -r build/${{ matrix.lib }}${{ matrix.ext }} downloads/${{ matrix.lib }}${{ matrix.ext }}
        fi
   
    - name: Artifacts - ${{ matrix.os }}
      uses: actions/upload-artifact@v2
      with: 
          name: assets-for-download
          path: downloads
