name: Build (GNU GCC/C++)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        ext: [ .so, .dll, .dylib ]
        lib: [ ice_cpu ]
        def: [ ICE_CPU_IMPL ]
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: Build - ${{ matrix.os }}

      run: |
        mkdir -p build
        yes | cp -r rebase/${{ matrix.lib }}.h build/${{ matrix.lib }}.h
        echo '#define ${{ matrix.def }}\n#include ${{ matrix.lib }}\n' > build/${{ matrix.lib }}.c
        gcc build/${{ matrix.lib }}.c -o build/${{ matrix.lib }}${{ matrix.ext }}
        rm -f build/*.c build/*.h
  
  archive-build-artifacts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        ext: [ .so, .dll, .dylib ]
        lib: [ ice_cpu ]
        def: [ ICE_CPU_IMPL ]
    
    steps:
    - name: Artifacts Setup & Update - ${{ matrix.os }}
      run: |
        mkdir -p downloads
        yes | cp -r build/${{ matrix.lib }}${{ matrix.ext }} downloads/${{ matrix.lib }}${{ matrix.ext }}
   
    - name: Artifacts #2 - ${{ matrix.os }}
      uses: actions/upload-artifact@v2
      with: 
          name: assets-for-download
          path: downloads
