name: ice_cpu

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Toolchain Checks
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y zip unzip libc6-dev-i386 mingw-w64

    - name: Build (Microsoft Windows, Linux)
      shell: bash
      run: |
        # Create directories for each platform...
        mkdir -p ice_libs_builds
        mkdir -p ice_libs_builds/ice_cpu
        mkdir -p ice_libs_builds/ice_cpu/linux32
        mkdir -p ice_libs_builds/ice_cpu/linux64
        mkdir -p ice_libs_builds/ice_cpu/win32
        mkdir -p ice_libs_builds/ice_cpu/win64

        cp -rf ${{ github.workspace }}/rebase/ice_cpu.h ${{ github.workspace }}/ice_libs_builds/ice_cpu.h
        printf '#define ICE_CPU_IMPL 1\n#include "ice_cpu.h"\n' > ${{ github.workspace }}/ice_libs_builds/ice_cpu.c
        
        # Linux (i386, x86_84)
        gcc -shared ${{ github.workspace }}/ice_libs_builds/ice_cpu.c -o ${{ github.workspace }}/ice_libs_builds/ice_cpu/linux32/ice_cpu.so -m32 -std=c89 -pedantic -Wall -Wextra -Werror -fPIC -Os -Ofast -lc
        gcc -shared ${{ github.workspace }}/ice_libs_builds/ice_cpu.c -o ${{ github.workspace }}/ice_libs_builds/ice_cpu/linux64/ice_cpu.so -std=c89 -pedantic -Wall -Wextra -Werror -fPIC -Os -Ofast -lc
        
        # Microsoft Windows (x86/i386, x86_64)
        i686-w64-mingw32-gcc -shared ${{ github.workspace }}/ice_libs_builds/ice_cpu.c -o ${{ github.workspace }}/ice_libs_builds/ice_cpu/win32/ice_cpu.dll -std=c89 -pedantic -Wall -Wextra -Werror -Os -Ofast -lkernel32
        x86_64-w64-mingw32-gcc -shared ${{ github.workspace }}/ice_libs_builds/ice_cpu.c -o ${{ github.workspace }}/ice_libs_builds/ice_cpu/win64/ice_cpu.dll -std=c89 -pedantic -Wall -Wextra -Werror -Os -Ofast -lkernel32
        
        rm -f ${{ github.workspace }}/ice_libs_builds/ice_cpu.c ${{ github.workspace }}/ice_libs_builds/ice_cpu.h
        
        mkdir -p ice_libs_downloads
        cp -r ${{ github.workspace }}/ice_libs_builds/ice_cpu ${{ github.workspace }}/ice_libs_downloads
        
        cd ice_libs_downloads
        zip -r ../ice_cpu_builds.zip ice_cpu
        
    - name: Uploading Artifacts
      uses: actions/upload-artifact@v2
      with: 
          name: ice_cpu_builds
          path: ${{ github.workspace }}/ice_cpu_builds.zip
