name: ice_cpu

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Toolchain Checks
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libc6-dev-i386
        sudo apt-get install -y mingw-w64

    - name: Build (Microsoft Windows, Linux)
      shell: bash
      run: |
        # Create directories for each platform...
        mkdir -p builds
        mkdir -p builds/ice_cpu
        mkdir -p builds/ice_cpu/linux32
        mkdir -p builds/ice_cpu/linux64
        mkdir -p builds/ice_cpu/win32
        mkdir -p builds/ice_cpu/win64

        cp -rf ${{ github.workspace }}/rebase/ice_cpu.h ${{ github.workspace }}/builds/ice_cpu.h
        printf '#define ICE_CPU_IMPL 1\n#include "ice_cpu.h"\n' > ${{ github.workspace }}/builds/ice_cpu.c
        
        # Linux (i386, x86_84)
        gcc -shared ${{ github.workspace }}/builds/ice_cpu.c -o ${{ github.workspace }}/builds/ice_cpu/linux32/ice_cpu.so -m32 -std=c89 -pedantic -Wall -Wextra -Werror -fPIC
        gcc -shared ${{ github.workspace }}/builds/ice_cpu.c -o ${{ github.workspace }}/builds/ice_cpu/linux64/ice_cpu.so -std=c89 -pedantic -Wall -Wextra -Werror -fPIC
        
        # Microsoft Windows (x86/i386, x86_64)
        i686-w64-mingw32-gcc -shared ${{ github.workspace }}/builds/ice_cpu.c -o ${{ github.workspace }}/builds/ice_cpu/win32/ice_cpu.dll -std=c89 -pedantic -Wall -Wextra -Werror
        x86_64-w64-mingw32-gcc -shared ${{ github.workspace }}/builds/ice_cpu.c -o ${{ github.workspace }}/builds/ice_cpu/win64/ice_cpu.dll -std=c89 -pedantic -Wall -Wextra -Werror
        
        rm -f ${{ github.workspace }}/builds/ice_cpu.c ${{ github.workspace }}/builds/ice_cpu.h
  
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Artifacts Setup & Update
      shell: bash
      run: |
        mkdir -p downloads
        mkdir -p downloads/ice_cpu
        mkdir -p downloads/ice_cpu/linux32
        mkdir -p downloads/ice_cpu/linux64
        mkdir -p downloads/ice_cpu/win32
        mkdir -p downloads/ice_cpu/win64

        cp -r ${{ github.workspace }}/builds/ice_cpu/linux32/ice_cpu.so ${{ github.workspace }}/downloads/ice_cpu/linux32/ice_cpu.so
        cp -r ${{ github.workspace }}/builds/ice_cpu/linux64/ice_cpu.so ${{ github.workspace }}/downloads/ice_cpu/linux64/ice_cpu.so
        cp -r ${{ github.workspace }}/builds/ice_cpu/win32/ice_cpu.dll ${{ github.workspace }}/downloads/ice_cpu/win32/ice_cpu.dll
        cp -r ${{ github.workspace }}/builds/ice_cpu/win64/ice_cpu.dll ${{ github.workspace }}/downloads/ice_cpu/win64/ice_cpu.dll
    
    - name: Uploading Artifacts
      uses: actions/upload-artifact@v2
      with: 
          name: ice_cpu_builds
          path: downloads/ice_cpu
